[parity]
chain = "/home/parity/.local/share/io.parity.ethereum/spec.json"
keys_path ="/home/parity/.local/share/io.parity.ethereum/keys"
[network]
port = 30300
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["/home/parity/.local/share/io.parity.ethereum/node.pwds"]
[mining]
min_gas_price = 1000000000
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 5000
reseal_max_period = 7000
[misc]
logging = "miner=trace,own_tx=trace"